### ISSUE TITLE
Versioriippumattoman sisällön lisäämismahdollisuus

### ISSUE THREAD

**Issue by ilkkarinne** [sykefi/ry-tietomallit#37]
Nykyversiossa kaikki tietyn tietomallin alla oleva sisältö on kiinnitetty tiettyyn linkitetyn GitHub-repon committiin, eli on riippuvaista tietystä julkaisuversiosta. Tämä onkin hyvä tietyn version speksien osalta, kosta tällöin ei vahingossakaan voi muuttaa speksiä ilman uutta julakisua, mutta lisäksi tarvitaan myös tietomallia yleisesti kuvaavaa, versioriippumatonta sisältöä, mm. tietomallin yleiskuvaus ja UKK.

Ajatus on toteuttaa tämä niin, että kunkin modulin konfigraatiossa on sekä yleiset navigaatiolinkit (juuritason nav_items), että kunkin version alaiset, versiokohtaiset linkit. Ensin mainituille tuotetaan versionumerottomat linkkipolut navigaatioon ja jälkimmäisille versionumerolliset:
```yaml
versions:
  - id: "v1.0"
    title: "Asema- ja yleiskaavan tietomallit -projektin lopputulos"
    path: "v1.0"
    default: true
    nav_items:
    - id: "looginenmalli"
        title: "Looginen tietomalli"
        heading: true
        subitems:
          - id: "dokumentaatio"
            title: "Dokumentaatio"
...
  - id: "dev"
    title: "Seuraava kehitysversio"
    path: "dev"
    development: true
    dependencies:
      - module: "yhteisetkomponentit"
        version: "dev"
    nav_items:
    - id: "looginenmalli"
        title: "Looginen tietomalli"
        heading: true
        subitems:
          - id: "dokumentaatio"
            title: "Dokumentaatio"
...
basepath: "kaavatiedot"
note: "Fyysiset mallit (Kaava-JSON ja Postgre) on siirretty Asema- ja yleiskaavojen tietomallit -kehitysprojektin alle"
nav_items:
  - id: "johdanto"
    title: "Johdanto"
    path: ""
    file: "index.md"
    default: true
- id: "ukk"
    title: "Usein kysytyt kysymykset"
    path: "ukk.html"
    file: "ukk.md"
```

Käyttöliittymässä versioriippumattomat navigointilinkit tulisivat vasemman reunan modulin navigointipalkissa modulin otsikon ja versiovalitsimen väliin.

Versioriippumattomat sisältösivut tallennetaan suoraan ry-tietomallit-repoon ko. tietomallin juurihakemiston alle, esim. [docs/kaavatiedot/](..docs/kaavatiedot/), ja siellä nykyisin oleva uudelleenohjaus oletusversion oletussivulle poistuisi.

Tässä pitää huomioida myös versiovalitsimen toiminnan muutos: Nykyisellään uuden version valinta vaihtaa nykyisen sivun (osoitteesta) vain versionumeron toiseen, eli oletetaan, että kaikissa versioissa on samat sivut. Tämä on käyttäjäystävällistä, kun versionvaihdossa sama sivu tulee näkyviin automattisesti eikä sitä tarvitse uudelleen etsiä. Muutoksen yhteydessä pitää päättää onko mahdollista vielä pyrkiä tähän, kun eri versiossa voi olla eri sivut, vai ohjataanko käyttäjä valitun version oletusivulle.
